### ISSUE TITLE
Appears that `@dell/clarity-react` isn't released via npmjs.com

### ISSUE THREAD

**Issue by trackerglen** [EMCECS/clarity-react#72]
Instructions in your readme suggest installing via `yarn add @dell/clarity-react`, but with a default yarn (or npm) CLI installation, the package is not found, and searching on npmjs.com seems to indicate that `@dell/clarity-react` (or any `@dell`-prefix package) is not present.  Is there an alternate NPM registry that should be used for installation?

Background:  Hi!  I'm a member of the team working on Pivotal Tracker (www.pivotaltracker.com).  We (all of Pivotal Software, including our team) have recently been acquired by VMware.  So, it turns out that we and y'all are now both in the big, happy Dell corporate family.  One of the things we're currently working on is a new, streamlined alternative of the Tracker web application.  We've been building it using React, trying to get by with a simple style guide, and discussing working to build out our own design system.  With the acquisition we've decided to instead shift our app to use Clarity.  And since we're in React, we've started using your `clarity-react`.  Given this installation problem, we've resorted to building your code locally and including the built library in our source control -- obviously not the best possible process.

Please advise whether you'd suggest that we continue this way, or if there's a better alternative that we've missed.  Thanks in advance, glen.

**Comment by ben-schumacher** [comment]
Hi @trackerglen, apologies for the confusion.  We haven't yet officially published to npm.  Right now, _we_ are aligning the @dell/clarity-react package in our UI projects to the tagged release in this repo.   You might consider doing the same so as to have a bit more control over what version of the package your using.  Would look something like this in your package.json.

`"@dell/clarity-react": "https://github.com/EMCECS/clarity-react/archive/0.20.0.tar.gz"`

Ideally it would be awesome if we could submit a PR back into VMWare Clarity repo so these components become native functionality as right now they only support Angular.  If that doesn't happen (due to time constraints), I would assume we will push a 1.0 release to npm sometime in the first half of this year.

**Comment by trackerglen** [comment]
Thanks Ben, that's really helpful context and I'll close the issue.  Speaking of submitting PRs, we might be generating some little ones to y'all.  Definitely open to any feedback you have, when/if.
